using System;
using System.IO;
using GreenChainz.Revit.Models;
using iText.Kernel.Pdf;
using iText.Kernel.Colors;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;

namespace GreenChainz.Revit.Services
{
    public class PdfExportService
    {
        public void GenerateAuditReport(AuditResult audit, string outputPath)
        {
            try
            {
                using (PdfWriter writer = new PdfWriter(outputPath))
                using (PdfDocument pdf = new PdfDocument(writer))
                using (Document doc = new Document(pdf))
                {
                    // Header
                    doc.Add(new Paragraph("GreenChainz")
                        .SetFontSize(16)
                        .SetBold()
                        .SetFontColor(new DeviceRgb(34, 139, 34)));

                    doc.Add(new Paragraph($"Project: {audit.ProjectName}")
                        .SetFontSize(18)
                        .SetBold());
                    
                    doc.Add(new Paragraph($"Date: {audit.Date.ToShortDateString()}")
                        .SetFontSize(14));

                    doc.Add(new Paragraph("\n"));

                    // Carbon Score
                    doc.Add(new Paragraph("Overall Carbon Score")
                        .SetFontSize(14)
                        .SetBold()
                        .SetTextAlignment(TextAlignment.CENTER));
                    
                    doc.Add(new Paragraph($"{audit.OverallScore:N0} kgCO2e")
                        .SetFontSize(36)
                        .SetBold()
                        .SetFontColor(new DeviceRgb(34, 139, 34))
                        .SetTextAlignment(TextAlignment.CENTER));

                    doc.Add(new Paragraph("\n"));

                    // Summary
                    doc.Add(new Paragraph("Summary").SetFontSize(18).SetBold());
                    doc.Add(new Paragraph(audit.Summary ?? "No summary available."));
                    doc.Add(new Paragraph("\n"));

                    // Material Breakdown Table
                    doc.Add(new Paragraph("Material Breakdown").SetFontSize(18).SetBold());
                    
                    Table table = new Table(4).UseAllAvailableWidth();
                    
                    // Headers
                    table.AddHeaderCell(new Cell().Add(new Paragraph("Material").SetBold()));
                    table.AddHeaderCell(new Cell().Add(new Paragraph("Quantity").SetBold()));
                    table.AddHeaderCell(new Cell().Add(new Paragraph("Factor").SetBold()));
                    table.AddHeaderCell(new Cell().Add(new Paragraph("Total (kgCO2e)").SetBold()));

                    // Data rows
                    if (audit.Materials != null)
                    {
                        foreach (var material in audit.Materials)
                        {
                            table.AddCell(material.MaterialName ?? "Unknown");
                            table.AddCell(material.Quantity ?? "0");
                            table.AddCell(material.CarbonFactor.ToString("N2"));
                            table.AddCell(material.TotalCarbon.ToString("N0"));
                        }
                    }

                    doc.Add(table);
                    doc.Add(new Paragraph("\n"));

                    // Recommendations
                    doc.Add(new Paragraph("Recommendations").SetFontSize(18).SetBold());
                    
                    if (audit.Recommendations != null)
                    {
                        List list = new List().SetSymbolIndent(12).SetListSymbol("\u2022");
                        foreach (var rec in audit.Recommendations)
                        {
                            list.Add(new ListItem($"{rec.Description} (Potential Savings: {rec.PotentialSavings:N0} kgCO2e)"));
                        }
                        doc.Add(list);
                    }

                    doc.Add(new Paragraph("\n\n"));

                    // Footer
                    doc.Add(new Paragraph("Generated by GreenChainz.\nDisclaimer: This report is an estimate based on available data.")
                        .SetFontSize(10)
                        .SetTextAlignment(TextAlignment.CENTER));
                    
                    doc.Add(new Paragraph("Contact: support@greenchainz.com")
                        .SetFontSize(10)
                        .SetTextAlignment(TextAlignment.CENTER));
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error generating PDF: " + ex.Message, ex);
            }
        }
    }
}
