using System;
using System.IO;
using GreenChainz.Revit.Models;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using iText.Kernel.Colors;

namespace GreenChainz.Revit.Services
{
    public class ScorecardPdfService
    {
        public void ExportScorecard(SustainabilityScorecard scorecard, string filePath)
        {
            using (PdfWriter writer = new PdfWriter(filePath))
            using (PdfDocument pdf = new PdfDocument(writer))
            using (Document document = new Document(pdf))
            {
                // Title
                document.Add(new Paragraph("SUSTAINABILITY SCORECARD")
                    .SetFontSize(24)
                    .SetBold()
                    .SetFontColor(new DeviceRgb(27, 94, 32)));

                document.Add(new Paragraph($"{scorecard.ProjectName}")
                    .SetFontSize(16));
                document.Add(new Paragraph($"Generated: {scorecard.GeneratedDate:MMMM dd, yyyy}")
                    .SetFontSize(10)
                    .SetFontColor(ColorConstants.GRAY));

                document.Add(new Paragraph("\n"));

                // Overall Grade
                document.Add(new Paragraph($"OVERALL GRADE: {scorecard.OverallGrade}")
                    .SetFontSize(20)
                    .SetBold()
                    .SetFontColor(GetGradeColor(scorecard.OverallGrade)));
                document.Add(new Paragraph($"Score: {scorecard.OverallScore}/100")
                    .SetFontSize(12));

                document.Add(new Paragraph("\n"));

                // Three Key Metrics Table
                Table metricsTable = new Table(3).UseAllAvailableWidth();
                
                // EPD
                metricsTable.AddCell(CreateMetricCell("EPD COVERAGE", 
                    scorecard.EpdScore.Grade,
                    $"{scorecard.EpdScore.CoveragePercent:F0}%",
                    $"{scorecard.EpdScore.MaterialsWithEpd}/{scorecard.EpdScore.TotalMaterials} materials"));

                // GWP
                metricsTable.AddCell(CreateMetricCell("EMBODIED CARBON",
                    scorecard.GwpScore.Grade,
                    $"{scorecard.GwpScore.TotalGwp:N0} kgCO2e",
                    scorecard.GwpScore.ReductionDisplay));

                // Verification
                metricsTable.AddCell(CreateMetricCell("VERIFICATION",
                    scorecard.VerificationScore.Tier,
                    scorecard.VerificationScore.Breakdown,
                    ""));

                document.Add(metricsTable);

                document.Add(new Paragraph("\n"));

                // Material Breakdown
                document.Add(new Paragraph("MATERIAL BREAKDOWN")
                    .SetFontSize(14)
                    .SetBold());

                Table materialsTable = new Table(6).UseAllAvailableWidth();
                materialsTable.AddHeaderCell("Material");
                materialsTable.AddHeaderCell("Category");
                materialsTable.AddHeaderCell("Qty (m³)");
                materialsTable.AddHeaderCell("GWP");
                materialsTable.AddHeaderCell("EPD");
                materialsTable.AddHeaderCell("Tier");

                foreach (var mat in scorecard.Materials)
                {
                    materialsTable.AddCell(mat.Name);
                    materialsTable.AddCell(mat.Category);
                    materialsTable.AddCell($"{mat.Quantity:F2}");
                    materialsTable.AddCell($"{mat.TotalGwp:N0}");
                    materialsTable.AddCell(mat.HasEpd ? "Yes" : "No");
                    materialsTable.AddCell(mat.VerificationTier);
                }

                document.Add(materialsTable);

                document.Add(new Paragraph("\n"));

                // Compliance Summary
                document.Add(new Paragraph("COMPLIANCE SUMMARY")
                    .SetFontSize(14)
                    .SetBold());
                document.Add(new Paragraph($"Estimated LEED Points: {scorecard.EstimatedLeedPoints}"));
                document.Add(new Paragraph($"LEED Compliant: {(scorecard.LeedCompliant ? "Yes" : "No")}"));
                document.Add(new Paragraph($"Buy Clean Compliant: {(scorecard.BuyCleanCompliant ? "Yes" : "No")}"));

                // Footer
                document.Add(new Paragraph("\n\n"));
                document.Add(new Paragraph("Generated by GreenChainz | Data sources: EC3, CLF v2021")
                    .SetFontSize(8)
                    .SetFontColor(ColorConstants.GRAY));
            }
        }

        private Cell CreateMetricCell(string title, string grade, string value, string detail)
        {
            Cell cell = new Cell()
                .SetPadding(10)
                .SetBorder(new iText.Layout.Borders.SolidBorder(ColorConstants.LIGHT_GRAY, 1));

            cell.Add(new Paragraph(title)
                .SetFontSize(10)
                .SetFontColor(ColorConstants.GRAY));
            cell.Add(new Paragraph(grade)
                .SetFontSize(24)
                .SetBold()
                .SetFontColor(GetGradeColor(grade)));
            cell.Add(new Paragraph(value)
                .SetFontSize(12));
            if (!string.IsNullOrEmpty(detail))
            {
                cell.Add(new Paragraph(detail)
                    .SetFontSize(9)
                    .SetFontColor(ColorConstants.GRAY));
            }

            return cell;
        }

        private Color GetGradeColor(string grade)
        {
            switch (grade)
            {
                case "A":
                case "Platinum":
                    return new DeviceRgb(76, 175, 80);
                case "B":
                case "Gold":
                    return new DeviceRgb(255, 193, 7);
                case "C":
                case "Silver":
                    return new DeviceRgb(255, 152, 0);
                default:
                    return new DeviceRgb(244, 67, 54);
            }
        }
    }
}
